MODULE = tensorflow-liite-micro_frontend_lib

CFLAGS += -Wno-sign-compare

SRC = \
    filterbank.c \
    filterbank_util.c \
    frontend.c \
    frontend_util.c \
    log_scale.c \
    log_scale_util.c \
    log_lut.c \
    noise_reduction.c \
    noise_reduction_util.c \
    pcan_gain_control.c \
    pcan_gain_control_util.c \
    window.c \
    window_util.c \
    #

include $(RIOTBASE)/Makefile.base
