USEMODULE += cpp11-compat

USEPKG += flatbuffers
USEPKG += gemmlowp

USEMODULE += tensorflow-lite
USEMODULE += tensorflow-lite-c
USEMODULE += tensorflow-lite-core
USEMODULE += tensorflow-lite-kernels
USEMODULE += tensorflow-lite-kernels-internal
USEMODULE += tensorflow-lite-memory
USEMODULE += tensorflow-lite-micro-kernels
USEMODULE += tensorflow-liite-micro_features
USEMODULE += tensorflow-liite-micro_frontend
USEMODULE += tensorflow-liite-micro_frontend_ops
USEMODULE += tensorflow-liite-micro_frontend_lib
USEMODULE += tensorflow-liite-micro_frontend_lib_cpp

# C++ support on ESP32 in RIOT doesn't work with TensorFlow-Lite for the moment
FEATURES_BLACKLIST += arch_esp32
