MODULE = tensorflow-liite-micro_frontend

SRCXXEXT = cc
SRCXXEXCLUDE := $(wildcard *_test.$(SRCXXEXT))

CFLAGS += -DTF_LITE_STATIC_MEMORY
CXXEXFLAGS += -Wno-unused-parameter

NO_AUTO_SRC := 1
SRCXX := \
    #

include $(RIOTBASE)/Makefile.base
